“lab1”
valent2004/OOPLabs pull request #1
Opened 2023-09-06 07:42 UTC by valent2004

2023-09-06 07:43 UTC, valent2004 commented
Зроблено

2023-09-06 12:06 UTC, RuslanSlobodian requested changes

2023-09-06 12:06 UTC, RuslanSlobodian commented on lab1/lab1/src/Main.java
> +    public void CurDate() {System.out.println(java.time.LocalDateTime.now()); }
в редакторі коду IntelliJ IDEA

2023-09-06 12:06 UTC, RuslanSlobodian commented on lab1/lab1/src/Main.java
> +        System.out.println("f: " + main.f(main.multi(main.m, main.multi(main.t, main.multi(main.g, main.t))), main.c, main.t));
не передавай у метод f жодних параметрів!

2023-09-12 14:21 UTC, RuslanSlobodian requested changes

2023-09-12 14:21 UTC, RuslanSlobodian commented on lab1/lab1/src/Main.java
> +    public double сalc_f() {
Використовуй CamelCase для написання назв, а не snake case
має бути: сalcF()

2023-09-12 14:21 UTC, RuslanSlobodian commented on lab1/lab1/src/Main.java
> +    public double сalc_z() {
Використовуй CamelCase для написання назв, а не snake case

2023-09-12 14:21 UTC, RuslanSlobodian commented on lab1/lab1/src/Main.java
> +    double m;
Чому всі атрибути є package-private  ?
Можливо забув прописати специфікатори доступу?

2023-09-12 14:21 UTC, RuslanSlobodian commented on lab1/lab1/src/Main.java
> +        m = c = t = b = g = 0;
Буде правильніше так:
m = c = t = b = g = 0.0;

2023-09-12 14:21 UTC, RuslanSlobodian commented on lab1/lab1/src/Main.java
> +        System.out.println(java.time.LocalDateTime.now());
Вивід дати не відповідає варіанту завдання
Використай клас SimpleDateFormat задавши патерн відновідно до варіанту завдання:
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("d.mm.yyyy - D");
        System.out.println(dateFormat.format(date));

2023-09-18 13:54 UTC, RuslanSlobodian approved these changes

2023-09-18 13:55 UTC, merged